CREATE TABLE IF NOT EXISTS balance_accounts (
    id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    openid     VARCHAR(64) NOT NULL UNIQUE COMMENT '微信 openid',
    balance    BIGINT NOT NULL DEFAULT 0 COMMENT '当前余额，单位分',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_balance_accounts_openid (openid)
);
